# Generated by Django 4.2.10 on 2024-03-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_options_alter_faq_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Shopping'), (2, 'Logging In'), (3, 'Applications'), (4, 'On the Day'), (5, 'Food Stalls'), (6, 'Buskers')], default=1),
        ),
    ]
