# Generated by Django 4.2.11 on 2024-03-15 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_faqcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(default='Shopping', on_delete=django.db.models.deletion.CASCADE, to='faq.faqcategory'),
        ),
    ]
