# Generated by Django 4.2.14 on 2024-11-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_email", models.TextField(verbose_name="from email")),
                ("recipients", models.TextField(verbose_name="recipients")),
                ("subject", models.TextField(verbose_name="subject")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "ok",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="ok"
                    ),
                ),
                (
                    "date_sent",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="date sent"
                    ),
                ),
                (
                    "html_message",
                    models.TextField(blank=True, verbose_name="HTML message"),
                ),
            ],
            options={
                "verbose_name": "email",
                "verbose_name_plural": "emails",
                "ordering": ("-date_sent",),
            },
        ),
    ]
