# Generated by Django 4.2.14 on 2024-11-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_email_stallholder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="html_message",
        ),
        migrations.RemoveField(
            model_name="email",
            name="recipients",
        ),
        migrations.AddField(
            model_name="email",
            name="recipient",
            field=models.TextField(
                default="g.todd@internet.co.nz", verbose_name="recipient"
            ),
            preserve_default=False,
        ),
    ]
