# Generated by Django 4.2.14 on 2024-11-16 21:43

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("fairs", "0076_site_has_power"),
        ("emails", "0003_remove_email_html_message_remove_email_recipients_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="email",
            managers=[
                ("emailhistorycurrentmgr", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="email",
            name="fair",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_fair",
                to="fairs.fair",
                verbose_name="fair",
            ),
            preserve_default=False,
        ),
    ]
