# Generated by Django 4.2.14 on 2024-11-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0005_alter_email_fair"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="email",
            managers=[],
        ),
    ]
