# Generated by Django 4.2.14 on 2024-11-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0058_alter_stallregistration_booking_status"),
        ("emails", "0006_alter_email_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="subject_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_types",
                to="registration.commenttype",
            ),
        ),
    ]
