# Generated by Django 4.1.5 on 2023-01-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CustomDBLogger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuslog",
            name="custom_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
