# Generated by Django 4.2.13 on 2024-06-25 19:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0056_stallregistration_is_invoiced'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLicenceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_sent', models.DateTimeField()),
                ('date_returned', models.DateTimeField(blank=True, null=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('batch_count', models.IntegerField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='FoodLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_status', django_fsm.FSMField(choices=[('Created', 'created'), ('Cancelled', 'submitted'), ('Rejected', 'rejected'), ('Approved', 'approved')], default='Created', max_length=50, verbose_name='Food Licence State')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField()),
                ('food_licence_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_licence_batch', to='foodlicence.foodlicencebatch')),
                ('food_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_licence', to='registration.foodregistration')),
            ],
        ),
    ]
