# Generated by Django 4.2.13 on 2024-07-03 15:01

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('foodlicence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlicence',
            name='licence_status',
            field=django_fsm.FSMField(choices=[('Created', 'created'), ('Batched', 'batched'), ('Submitted', 'submitted'), ('Rejected', 'rejected'), ('Approved', 'approved')], default='Created', max_length=50, verbose_name='Food Licence State'),
        ),
    ]
