# Generated by Django 4.2.13 on 2024-07-10 21:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodlicence', '0003_alter_foodlicence_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foodlicencebatch',
            managers=[
                ('foodlicencebatchcurrentmgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
