# Generated by Django 4.2.13 on 2024-07-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodlicence', '0004_alter_foodlicencebatch_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foodlicencebatch',
            managers=[
            ],
        ),
    ]
