# Generated by Django 4.2.16 on 2024-09-17 17:19

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('foodlicence', '0005_alter_foodlicencebatch_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlicence',
            name='licence_status',
            field=django_fsm.FSMField(choices=[('Created', 'created'), ('Staged', 'staged'), ('Batched', 'batched'), ('Submitted', 'submitted'), ('Rejected', 'rejected'), ('Approved', 'approved')], default='Created', max_length=50, verbose_name='Food Licence State'),
        ),
        migrations.AlterField(
            model_name='foodlicencebatch',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/2024'),
        ),
    ]
