# Generated by Django 4.2.14 on 2025-01-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodlicence", "0006_alter_foodlicence_licence_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlicencebatch",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/2025"),
        ),
    ]
