# Generated by Django 4.2.9 on 2024-02-07 22:35

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_invoiceitem_options_alter_invoice_gst_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_status',
            field=django_fsm.FSMField(choices=[('Pending', 'pending'), ('Cancelled', 'cancelled'), ('Completed', 'completed'), ('Failed', 'failed'), ('Reconciled', 'reconciled')], default='Pending', max_length=50, verbose_name='Payment State'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.paymenttype'),
        ),
    ]
