# Generated by Django 4.2.9 on 2024-02-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paymenthistory_amount_to_pay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='invoice',
            new_name='invoice',
        ),
    ]
