# Generated by Django 4.2.9 on 2024-02-11 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_invoice_number_paymenthistory_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='payment.invoice'),
        ),
    ]
