# Generated by Django 4.2.9 on 2024-02-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_paymenthistory_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'verbose_name_plural': 'payment_type_names'},
        ),
    ]
