# Generated by Django 4.2.9 on 2024-02-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_paymenttype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'verbose_name_plural': 'payment types'},
        ),
    ]
