# Generated by Django 4.2.10 on 2024-02-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_paymenttype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_sequence',
            field=models.IntegerField(default=1),
        ),
    ]
