# Generated by Django 4.2.10 on 2024-02-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_invoice_invoice_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='amount_reconciled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
