# Generated by Django 4.2.11 on 2024-04-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_paymenthistory_amount_reconciled'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
