# Generated by Django 4.2.11 on 2024-04-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_invoice_invoice_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='gst_value',
            new_name='gst_component',
        ),
    ]
