# Generated by Django 4.2.13 on 2024-06-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_discountitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountitem',
            name='invoice',
        ),
    ]
