# Generated by Django 4.2.13 on 2024-06-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_remove_discountitem_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountItem',
        ),
    ]
