# Generated by Django 4.2.13 on 2024-06-11 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0016_discountitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
