# Generated by Django 4.2.14 on 2024-07-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_discountitem_created_by_discountitem_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
