# Generated by Django 4.2.14 on 2024-08-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_paymenthistory_stripe_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='webhook_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
