# Generated by Django 4.2.14 on 2024-12-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0022_alter_paymenthistory_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="amount_credited",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
