# Generated by Django 3.2.9 on 2021-12-06 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone2',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(regex='/^(\\((03|04|06|07|09)\\)\\d{7})|(\\((021|022|025|027|028|029)\\)\\d{6,8})|((0508|0800|0900)\\d{5,8})$/')]),
        ),
    ]
