# Generated by Django 3.2.12 on 2022-03-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220314_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone2',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
