# Generated by Django 3.2.13 on 2022-06-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220316_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reference_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
