# Generated by Django 4.2.13 on 2024-07-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_org_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reference_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
