# Generated by Django 3.2.7 on 2021-09-23 04:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fair_year', models.CharField(default='2022', max_length=4)),
                ('fair_name', models.CharField(max_length=40)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_cancelled', models.DateTimeField(blank=True, default=None, null=True)),
                ('fair_description', models.TextField()),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Fairs',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=40)),
                ('original_event_date', models.DateTimeField()),
                ('postponement_event_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_cancelled', models.DateTimeField(blank=True, default=None, null=True)),
                ('event_description', models.TextField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_postponed', models.BooleanField(default=False)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fairs.fair')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
