# Generated by Django 3.2.7 on 2021-10-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0003_auto_20211005_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='original_event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='postponement_event_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
