# Generated by Django 3.2.7 on 2021-10-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0009_alter_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='created_by',
        ),
    ]
