# Generated by Django 3.2.7 on 2021-10-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0010_rename_user_event_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fair',
            old_name='user',
            new_name='created_by',
        ),
    ]
