# Generated by Django 3.2.8 on 2021-10-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0013_auto_20211012_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=40)),
                ('map_pdf', models.FileField(upload_to='media/maps')),
                ('trestle_source', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Zones',
            },
        ),
    ]
