# Generated by Django 3.2.8 on 2021-10-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0015_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Available to be booked'), (2, 'Allocated to a stallholder'), (3, 'Pending finalisation of the booking'), (4, 'Booked')], default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sites', to='fairs.event', verbose_name='event')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sites', to='fairs.site', verbose_name='site')),
            ],
        ),
    ]
