# Generated by Django 3.2.8 on 2021-10-28 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0019_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
