# Generated by Django 3.2.8 on 2021-10-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0020_alter_inventoryitem_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_code',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
    ]
