# Generated by Django 3.2.8 on 2021-10-29 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0021_zone_zone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fairs.inventoryitem'),
        ),
    ]
