# Generated by Django 3.2.8 on 2021-11-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0022_alter_site_site_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name_plural': 'InventoryItems'},
        ),
    ]
