# Generated by Django 3.2.8 on 2021-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0024_alter_eventsite_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsite',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Available to be booked'), (2, 'Allocated to a stallholder'), (3, 'Pending finalisation of the booking'), (4, 'Booked'), (5, 'Not available for this event')], default=1),
        ),
    ]
