# Generated by Django 3.2.9 on 2021-12-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0027_auto_20211204_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemFair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item_fair', to='fairs.fair', verbose_name='fair')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item_fair', to='fairs.inventoryitem', verbose_name='inventory_items')),
            ],
        ),
        migrations.AddField(
            model_name='fair',
            name='inventory_items',
            field=models.ManyToManyField(related_name='fairs', through='fairs.InventoryItemFair', to='fairs.InventoryItem'),
        ),
    ]
