# Generated by Django 3.2.9 on 2021-12-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0028_auto_20211213_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerItem',
            fields=[
                ('inventoryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fairs.inventoryitem')),
                ('power_connection', models.BooleanField(default=False)),
            ],
            bases=('fairs.inventoryitem',),
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='site_size',
        ),
        migrations.CreateModel(
            name='SiteItem',
            fields=[
                ('inventoryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fairs.inventoryitem')),
                ('site_size', models.CharField(max_length=40)),
            ],
            bases=('fairs.inventoryitem',),
        ),
    ]
