# Generated by Django 3.2.9 on 2021-12-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0029_auto_20211214_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteitem',
            name='inventoryitem_ptr',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_power_connection',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PowerItem',
        ),
        migrations.DeleteModel(
            name='SiteItem',
        ),
    ]
