# Generated by Django 3.2.9 on 2021-12-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0030_auto_20211215_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='site_size',
            field=models.CharField(default='', max_length=40),
        ),
    ]
