# Generated by Django 3.2.9 on 2021-12-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0033_alter_inventoryitem_site_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemfair',
            name='price_rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fair Price'), (2, 'Daily Price')], default=1),
        ),
    ]
