# Generated by Django 3.2.9 on 2021-12-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0034_inventoryitemfair_price_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Site'), (2, 'PowerPoint'), (3, 'Health & Safety'), (4, 'Food Licence'), (5, 'Trestle')], default=1),
        ),
    ]
