# Generated by Django 3.2.10 on 2021-12-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0036_remove_inventoryitem_is_power_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_box_name', models.CharField(max_length=100)),
                ('socket_count', models.IntegerField()),
                ('max_load', models.DecimalField(decimal_places=4, max_digits=10)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerbox', to='fairs.zone', verbose_name='zone')),
            ],
        ),
        migrations.CreateModel(
            name='EventPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_load', models.DecimalField(decimal_places=5, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_power', to='fairs.event', verbose_name='event')),
                ('power_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_power', to='fairs.powerbox', verbose_name='power_box')),
            ],
            options={
                'unique_together': {('event', 'power_box')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='power_boxes',
            field=models.ManyToManyField(related_name='events', through='fairs.EventPower', to='fairs.PowerBox'),
        ),
    ]
