# Generated by Django 3.2.10 on 2021-12-21 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fairs', '0037_auto_20211220_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbox',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerbox_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='powerbox',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerbox',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='powerbox',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerbox_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
