# Generated by Django 3.2.10 on 2021-12-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0038_auto_20211221_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
