# Generated by Django 3.2.11 on 2022-01-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0041_event_event_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='power_boxes',
        ),
        migrations.AddField(
            model_name='eventpower',
            name='sockets_used',
            field=models.IntegerField(default=0),
        ),
    ]
