# Generated by Django 3.2.13 on 2022-05-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0043_alter_eventsite_site_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbox',
            name='power_box_description',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
