# Generated by Django 3.2.13 on 2022-06-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0044_powerbox_power_box_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('map_pdf', models.FileField(upload_to='media/maps/2022')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_map', to='fairs.zone', verbose_name='fair')),
            ],
            options={
                'unique_together': {('year', 'map_pdf')},
            },
        ),
    ]
