# Generated by Django 3.2.13 on 2022-07-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0047_sitehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitehistory',
            old_name='Year',
            new_name='year',
        ),
    ]
