# Generated by Django 3.2.13 on 2022-07-10 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0013_foodregistration_has_food_prep'),
        ('fairs', '0048_rename_year_sitehistory_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_power', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_allocation', to='fairs.eventpower', verbose_name='event_power')),
                ('event_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_allocation', to='fairs.eventsite', verbose_name='event_site')),
                ('stall_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_allocation', to='registration.stallregistration', verbose_name='stall_registration')),
                ('stallholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_allocation', to=settings.AUTH_USER_MODEL, verbose_name='custom_user')),
            ],
        ),
    ]
