# Generated by Django 3.2.14 on 2022-07-18 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fairs', '0049_siteallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siteallocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
