# Generated by Django 3.2.14 on 2022-07-31 21:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fairs', '0050_auto_20220718_1110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='siteallocation',
            unique_together={('stallholder', 'event_site')},
        ),
    ]
