# Generated by Django 3.2.15 on 2022-10-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0052_alter_event_event_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_sequence',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First Event'), (2, 'Second Event')], default=1),
        ),
    ]
