# Generated by Django 3.2.16 on 2022-11-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0054_alter_siteallocation_stall_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsite',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
