# Generated by Django 4.1.4 on 2023-01-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairs", "0055_eventsite_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteallocation",
            name="on_hold",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="zonemap",
            name="map_pdf",
            field=models.FileField(upload_to="maps/2023"),
        ),
        migrations.AlterField(
            model_name="zonemap",
            name="year",
            field=models.CharField(default="2023", max_length=4),
        ),
    ]
