# Generated by Django 4.1.5 on 2023-01-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairs", "0056_siteallocation_on_hold_alter_zonemap_map_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="site_name",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
