# Generated by Django 4.1.5 on 2023-01-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairs", "0057_alter_site_site_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_name",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="fair",
            name="fair_name",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="item_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="powerbox",
            name="power_box_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="zone",
            name="zone_name",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
