# Generated by Django 4.1.5 on 2023-01-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairs", "0059_site_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="site_note",
            field=models.TextField(default=None, null=True),
        ),
    ]
