# Generated by Django 4.1.5 on 2023-01-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairs", "0060_site_site_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="site_note",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
