# Generated by Django 4.1.5 on 2023-01-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairs", "0061_alter_site_site_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="fair",
            name="allocation_email",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
