# Generated by Django 4.1.5 on 2023-01-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fairs", "0062_fair_allocation_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fair",
            old_name="allocation_email",
            new_name="allocation_email_date",
        ),
    ]
