# Generated by Django 4.1.5 on 2023-02-03 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fairs", "0064_rename_is_active_fair_is_activated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteallocation",
            name="stallholder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site_allocation",
                to=settings.AUTH_USER_MODEL,
                verbose_name="stallholder",
            ),
        ),
    ]
