# Generated by Django 4.1.7 on 2023-04-11 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0034_registrationcomment_is_archived"),
        ("fairs", "0065_alter_siteallocation_stallholder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteallocation",
            name="stall_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_allocation",
                to="registration.stallregistration",
                verbose_name="stall_registration",
            ),
        ),
    ]
