# Generated by Django 4.2.9 on 2024-01-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0067_alter_zonemap_map_pdf_alter_zonemap_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Site'), (2, 'PowerPoint'), (3, 'Health & Safety'), (4, 'Food Licence'), (5, 'Trestle'), (6, 'Vehicle')], default=1),
        ),
    ]
