# Generated by Django 4.2.10 on 2024-02-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0069_alter_inventoryitemfair_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemfair',
            name='is_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitemfair',
            name='is_refundable',
            field=models.BooleanField(default=True),
        ),
    ]
