# Generated by Django 4.2.14 on 2024-08-10 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fairs", "0072_fair_is_open"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zone",
            name="trestle_source",
        ),
    ]
