# Generated by Django 4.2.14 on 2024-08-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0073_remove_zone_trestle_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='trestle_source',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Red'), (2, 'Blue')], default=None, null=True),
        ),
    ]
