# Generated by Django 4.2.14 on 2024-08-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0074_zone_trestle_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitehistory',
            name='site_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_size_name', to='fairs.inventoryitem'),
        ),
    ]
