# Generated by Django 4.2.14 on 2024-10-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairs", "0075_sitehistory_site_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="has_power",
            field=models.BooleanField(default=False),
        ),
    ]
