# Generated by Django 4.2.14 on 2025-01-11 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fairs", "0077_site_powerbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitehistory",
            name="had_fair_site_move",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitehistory",
            name="had_late_cancel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitehistory",
            name="history_note",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="sitehistory",
            name="number_events",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="zonemap",
            name="map_pdf",
            field=models.FileField(upload_to="maps/2025"),
        ),
        migrations.AlterField(
            model_name="zonemap",
            name="year",
            field=models.CharField(default="2025", max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name="sitehistory",
            unique_together={("stallholder", "site", "year")},
        ),
    ]
