# Generated by Django 4.2.14 on 2025-04-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairs", "0078_sitehistory_had_fair_site_move_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zonemap",
            name="map_pdf",
            field=models.FileField(
                upload_to="maps/<django.db.models.fields.CharField>"
            ),
        ),
        migrations.AlterField(
            model_name="zonemap",
            name="year",
            field=models.CharField(max_length=4),
        ),
    ]
