# Generated by Django 3.2.11 on 2022-01-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20220121_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='stallregistration',
            name='products_on_site',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stallregistration',
            name='stall_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
