# Generated by Django 3.2.11 on 2022-01-25 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0040_zone_location'),
        ('registration', '0005_auto_20220124_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stallregistration',
            name='event_site',
        ),
        migrations.AddField(
            model_name='stallregistration',
            name='event_site_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stall_registrations', to='fairs.eventsite', verbose_name='eventsitefirst'),
        ),
    ]
