# Generated by Django 3.2.11 on 2022-01-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0041_event_event_sequence'),
        ('registration', '0006_auto_20220125_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stallregistration',
            name='event_site_first',
        ),
        migrations.AddField(
            model_name='stallregistration',
            name='event_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_first', to='fairs.event', verbose_name='events_first'),
        ),
        migrations.AddField(
            model_name='stallregistration',
            name='event_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_second', to='fairs.event', verbose_name='event_second'),
        ),
    ]
