# Generated by Django 3.2.11 on 2022-01-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0041_event_event_sequence'),
        ('registration', '0007_auto_20220126_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stallregistration',
            name='event_first',
        ),
        migrations.RemoveField(
            model_name='stallregistration',
            name='event_second',
        ),
        migrations.AddField(
            model_name='stallregistration',
            name='event_site_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_site_first', to='fairs.eventsite', verbose_name='eventsitefirst'),
        ),
        migrations.AddField(
            model_name='stallregistration',
            name='event_site_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_site_second', to='fairs.eventsite', verbose_name='eventsitesecond'),
        ),
    ]
