# Generated by Django 3.2.11 on 2022-02-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0043_alter_eventsite_site_status'),
        ('registration', '0008_auto_20220126_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stallregistration',
            name='event_power',
        ),
        migrations.AddField(
            model_name='stallregistration',
            name='event_power_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_power_first', to='fairs.eventpower', verbose_name='eventpowerfirst'),
        ),
        migrations.AddField(
            model_name='stallregistration',
            name='event_power_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_power_second', to='fairs.eventpower', verbose_name='eventpowersecond'),
        ),
    ]
