# Generated by Django 3.2.12 on 2022-03-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20220221_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodprepequipreq',
            name='electrical_powered',
        ),
        migrations.RemoveField(
            model_name='foodprepequipreq',
            name='gas_powered',
        ),
        migrations.AddField(
            model_name='foodprepequipreq',
            name='how_powered',
            field=models.CharField(choices=[(1, 'Electric Powered'), (2, 'Gas Powered')], default=1, max_length=11),
        ),
    ]
