# Generated by Django 3.2.12 on 2022-03-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20220314_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodregistration',
            name='has_food_storage_prep',
        ),
        migrations.AddField(
            model_name='foodregistration',
            name='food_storage_prep',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
