# Generated by Django 3.2.15 on 2022-09-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_foodregistration_has_food_prep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stallregistration',
            name='event_power_first',
        ),
        migrations.RemoveField(
            model_name='stallregistration',
            name='event_power_second',
        ),
        migrations.RemoveField(
            model_name='stallregistration',
            name='event_site_first',
        ),
        migrations.RemoveField(
            model_name='stallregistration',
            name='event_site_second',
        ),
    ]
