# Generated by Django 3.2.15 on 2022-09-15 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0051_alter_siteallocation_unique_together'),
        ('registration', '0014_auto_20220913_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='stallregistration',
            name='fair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fairs.fair'),
            preserve_default=False,
        ),
    ]
