# Generated by Django 3.2.15 on 2022-10-01 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0052_alter_event_event_sequence'),
        ('registration', '0015_stallregistration_fair'),
    ]

    operations = [
        migrations.AddField(
            model_name='stallregistration',
            name='site_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_size_requirement', to='fairs.inventoryitem'),
        ),
    ]
