# Generated by Django 3.2.15 on 2022-10-07 15:13

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_stallregistration_site_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stallregistration',
            name='booking_status',
            field=django_fsm.FSMField(choices=[('Created', 'Created'), ('Submitted', 'Submitted'), ('Invoiced', 'Invoiced'), ('Manual Payment', 'Manual Payment'), ('Poli Payment', 'Poli Payment'), ('Stripe Payment', 'Stripe Payment'), ('Payment Completed', 'Payment Completed'), ('Allocation Review', 'Allocation Review'), ('Allocation Pending', 'Allocation Pending'), ('Allocation Approved', 'Allocation Approved'), ('Allocation Cancelled', 'Allocation Rejected'), ('Refund Review', 'Refund Review'), ('Refund Donated', 'Refund Donated'), ('Refund Rejected', 'Refund Rejected'), ('Refund Approved', 'Refund Approved'), ('Booked', 'Booked'), ('Cancelled', 'Cancelled')], default='Created', max_length=50, protected=True, verbose_name='Registration State'),
        ),
    ]
