# Generated by Django 3.2.15 on 2022-10-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_alter_stallregistration_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stallregistration',
            options={'verbose_name': 'stallregistration', 'verbose_name_plural': 'stallregistrations'},
        ),
    ]
