# Generated by Django 3.2.15 on 2022-10-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_alter_stallregistration_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodregistration',
            options={'verbose_name': 'foodegistration', 'verbose_name_plural': 'foodegistrations'},
        ),
        migrations.AlterField(
            model_name='foodregistration',
            name='certificate_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodregistration',
            name='food_prep_equipment',
            field=models.ManyToManyField(blank=True, null=True, related_name='food_registration', through='registration.FoodPrepEquipReq', to='registration.FoodPrepEquipment'),
        ),
    ]
