# Generated by Django 3.2.15 on 2022-10-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20221011_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodregistration',
            name='food_prep_equipment',
            field=models.ManyToManyField(related_name='food_registration', through='registration.FoodPrepEquipReq', to='registration.FoodPrepEquipment'),
        ),
    ]
