# Generated by Django 3.2.15 on 2022-10-13 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_alter_foodregistration_food_prep_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodprepequipreq',
            name='food_prep_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_prep_equip', to='registration.foodprepequipment', verbose_name='FoodPrepEquipment'),
        ),
        migrations.AlterField(
            model_name='foodprepequipreq',
            name='food_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_prep_equip_req', to='registration.foodregistration', verbose_name='FoodPrepEquipmentRequired'),
        ),
    ]
