# Generated by Django 3.2.15 on 2022-10-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_auto_20221013_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodprepequipreq',
            options={'verbose_name': 'foodprepequiprequired', 'verbose_name_plural': 'foodprepequiprequirements'},
        ),
    ]
