# Generated by Django 3.2.16 on 2022-11-13 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_auto_20221017_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationcomment',
            options={'ordering': ('date_created',)},
        ),
        migrations.AddField(
            model_name='registrationcomment',
            name='comment_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='registration.registrationcomment'),
        ),
        migrations.AddField(
            model_name='registrationcomment',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registrationcomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
