# Generated by Django 3.2.16 on 2022-11-14 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0025_auto_20221113_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'CommentTypes',
                'ordering': ('type_name',),
            },
        ),
        migrations.RemoveField(
            model_name='registrationcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='registrationcomment',
            name='stall_registration',
        ),
        migrations.AddField(
            model_name='registrationcomment',
            name='stallholder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationcomment',
            name='comment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_types', to='registration.commenttype'),
        ),
    ]
