# Generated by Django 3.2.16 on 2022-11-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_auto_20221114_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcomment',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
