# Generated by Django 3.2.16 on 2022-11-14 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0027_registrationcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcomment',
            name='stallholder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
