# Generated by Django 3.2.16 on 2022-11-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_alter_registrationcomment_stallholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcomment',
            name='comment_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='registration.registrationcomment'),
        ),
    ]
