# Generated by Django 4.1.6 on 2023-02-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0031_stallregistration_vehicle_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stallregistration",
            name="manager_vehicle_registration",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="stallregistration",
            name="stall_shelter",
            field=models.TextField(blank=True, null=True),
        ),
    ]
