# Generated by Django 4.1.6 on 2023-02-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registration",
            "0032_stallregistration_manager_vehicle_registration_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stallregistration",
            name="vehicle_image",
            field=models.ImageField(blank=True, null=True, upload_to="vehicles/2023"),
        ),
        migrations.AlterField(
            model_name="stallregistration",
            name="vehicle_length",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="stallregistration",
            name="vehicle_width",
            field=models.FloatField(default=0),
        ),
    ]
