# Generated by Django 4.1.9 on 2023-06-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0035_foodprepequipreq_equipment_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodprepequipreq",
            name="how_powered",
            field=models.CharField(
                choices=[("1", "Electric Powered"), ("2", "Gas Powered")],
                default="1",
                max_length=11,
            ),
        ),
    ]
