# Generated by Django 4.1.9 on 2023-07-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0038_alter_foodregistration_food_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodregistration",
            name="is_valid",
            field=models.BooleanField(default=False),
        ),
    ]
