# Generated by Django 4.1.10 on 2023-07-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0040_alter_foodregistration_food_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodregistration",
            name="food_registration_certificate",
            field=models.FileField(blank=True, upload_to="food_certificates/2023"),
        ),
    ]
