# Generated by Django 4.1.10 on 2023-07-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0041_alter_foodregistration_food_registration_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodregistration",
            name="cert_filetype",
            field=models.CharField(blank=True, default="image", max_length=50),
        ),
    ]
