# Generated by Django 4.1.10 on 2023-07-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0043_alter_foodregistration_food_display_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodregistration",
            name="food_prep_equipment",
            field=models.ManyToManyField(
                blank=True,
                related_name="food_registration",
                through="registration.FoodPrepEquipReq",
                to="registration.foodprepequipment",
            ),
        ),
    ]
