# Generated by Django 4.1.10 on 2023-07-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0044_alter_foodregistration_food_prep_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodregistration",
            name="food_registration_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="food_certificates/2023"
            ),
        ),
    ]
