# Generated by Django 4.1.10 on 2023-07-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0045_alter_foodregistration_food_registration_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodregistration",
            name="cert_filetype",
            field=models.CharField(
                blank=True, default="image", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="foodregistration",
            name="food_fair_consumed",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="foodregistration",
            name="has_food_certificate",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
