# Generated by Django 4.1.10 on 2023-08-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0047_stallregistration_multi_site_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodregistration",
            name="registration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_registration",
                to="registration.stallregistration",
            ),
        ),
    ]
