# Generated by Django 4.1.10 on 2023-08-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0050_alter_foodregistration_food_prep_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="stallregistration",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
