# Generated by Django 4.2.9 on 2024-01-22 13:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0052_alter_foodregistration_food_registration_certificate_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='additionalsiterequirement',
            managers=[
                ('additionalsiterequirementmgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
