# Generated by Django 4.2.9 on 2024-01-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0053_alter_additionalsiterequirement_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='additionalsiterequirement',
            managers=[
            ],
        ),
    ]
