# Generated by Django 4.2.10 on 2024-02-18 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0069_alter_inventoryitemfair_inventory_item'),
        ('registration', '0054_alter_additionalsiterequirement_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stallcategory',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_inventory_item', to='fairs.inventoryitem'),
        ),
    ]
