# Generated by Django 4.2.11 on 2024-04-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0055_alter_stallcategory_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stallregistration',
            name='is_invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
