# Generated by Django 4.2.14 on 2025-01-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0058_alter_stallregistration_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodregistration",
            name="food_registration_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="food_certificates/2025"
            ),
        ),
        migrations.AlterField(
            model_name="stallregistration",
            name="vehicle_image",
            field=models.ImageField(blank=True, null=True, upload_to="vehicles/2025"),
        ),
    ]
