# Generated by Django 4.2.14 on 2025-01-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registration",
            "0059_alter_foodregistration_food_registration_certificate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="foodprepequipment",
            name="power_load_amps",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
