# Generated by Django 4.2.14 on 2025-01-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0060_foodprepequipment_power_load_amps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodprepequipment",
            name="power_load_amps",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
