# Generated by Django 4.2.14 on 2025-03-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0062_stallregistration_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodregistration",
            name="uses_compostable_containers",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodregistration",
            name="uses_compostable_cups",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
