# Generated by Django 4.2.14 on 2025-10-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0063_foodregistration_uses_compostable_containers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stallcategory",
            name="for_selling_food",
            field=models.BooleanField(
                default=False,
                help_text="Check if this category represents food-related stalls",
            ),
        ),
    ]
