# Generated by Django 4.2.14 on 2025-10-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0064_stallcategory_for_selling_food"),
    ]

    operations = [
        migrations.AddField(
            model_name="stallregistration",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
