# fairs/urls.py


from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from fairs.views import (
    FairListView,
    FairCreateView,
    FairDetailUpdateView,
    EventCreateView,
    EventListView,
    EventDetailUpdateView,
    EventPowerCreateView,
    EventPowerListView,
    EventPowerDetailUpdateView,
    LocationCreateView,
    LocationDetailUpdateView,
    LocationListView,
    ZoneCreateView,
    ZoneListView,
    ZoneDetailUpdateView,
    ZoneMapCreateView,
    ZoneMapDetailUpdateView,
    pdf_view,
    site_allocation_create,
    SiteAllocationUpdateView,
    site_allocation_listview,
    siteallocation_delete_view,
    SiteCreateView,
    SiteListView,
    site_listview,
    SiteDetailUpdateView,
    stallholder_select,
    EventSiteCreateView,
    event_site_listview,
    EventSiteDetailUpdateView,
    InventoryItemCreateView,
    InventoryItemListView,
    InventoryItemDetailUpdateView,
    InventoryItemFairListView,
    InventoryItemFairCreateView,
    InventoryItemFairDetailUpdateView,
    PowerBoxListView,
    PowerBoxDetailUpdateView,
    PowerBoxCreateView,
    site_dashboard_view,
    stall_registration_dashboard_view,
    stallregistration_detail_view,
    setup_process_dashboard_view,
    messages_dashboard_view,
    stallholder_history_dashboard_view,
    set_message_to_done,
    set_message_to_active,
    stallregistration_siteallocation_view,
    stallregistration_move_cancel_view,
    stallregistration_search_dashboard_view,
    stallregistrations_without_power_view, powerbox_connections_view,
    stallregistrations_by_powerbox_view,
)

app_name = 'fair'  # This is the namespace, so you can reverse urls with fair:*

urlpatterns = [

    path('fair/', FairListView.as_view(), name='fair-list'),
    path('fair/<int:pk>', FairDetailUpdateView.as_view(), name='fair-detail'),
    path('event/', EventListView.as_view(), name='event-list'),
    path('event/<int:pk>', EventDetailUpdateView.as_view(), name='event-detail'),
    path('location/', LocationListView.as_view(), name='location-list'),
    path('location/create/', LocationCreateView.as_view(), name='location-create'),
    path('location/,<int:pk>', LocationDetailUpdateView.as_view(), name='location-detail'),
    path('zone/', ZoneListView.as_view(), name='zone-list'),
    path('zone/,<int:pk>', ZoneDetailUpdateView.as_view(), name='zone-detail'),
    path('zonemap/upload/', ZoneMapCreateView.as_view(), name='zonemap-create'),
    path('zonemap/,<int:pk>', ZoneMapDetailUpdateView.as_view(), name='zonemap-detail'),
    path('zonemap/<int:pk>/view/', pdf_view, name='view-map'),
    path('site/', site_listview, name='site-list'),
    path('site/,<int:pk>', SiteDetailUpdateView.as_view(), name='site-detail'),
    path('eventsite/', event_site_listview, name='eventsite-list'),
    path('eventsite/,<int:pk>', EventSiteDetailUpdateView.as_view(), name='eventsite-detail'),
    path('inventoryitem/', InventoryItemListView.as_view(), name='inventoryitem-list'),
    path('inventoryitem/,<int:pk>', InventoryItemDetailUpdateView.as_view(), name='inventoryitem-detail'),
    path('inventoryitemfair/', InventoryItemFairListView.as_view(), name='inventoryitemfair-list'),
    path('inventoryitemfair/,<int:pk>', InventoryItemFairDetailUpdateView.as_view(), name='inventoryitemfair-detail'),
    path('powerbox/', PowerBoxListView.as_view(), name='powerbox-list'),
    path('powerbox/,<int:pk>', PowerBoxDetailUpdateView.as_view(), name='powerbox-detail'),
    path('eventpower/', EventPowerListView.as_view(), name='eventpower-list'),
    path('eventpower/,<int:pk>', EventPowerDetailUpdateView.as_view(), name='eventpower-detail'),
    path('dashboard/process/', setup_process_dashboard_view, name='setup-dashboard'),
    path('dashboard/site/', site_dashboard_view, name='site-dashboard'),
    path('dashboard/registrations/', stall_registration_dashboard_view, name='registration-dashboard'),
    path('dashboard/messages/', messages_dashboard_view, name='messages-dashboard'),
    path('dashboard/history/', stallholder_history_dashboard_view, name='history-dashboard'),
    path('dashboard/search-registrations/', stallregistration_search_dashboard_view, name='stallregistration-search'),
    path('registration/management/', site_dashboard_view, name='stallregistration-list'),
    path('registration/<int:id>/siteallocation/', stallregistration_siteallocation_view, name='stallregistration-siteallocation'),
    path('registration/<int:id>/move/', stallregistration_move_cancel_view, name='stallregistration-move-siteallocation'),
    path('stallregistration/<stallregistration_id>/', stallregistration_detail_view, name='stallregistration-detail'),
    path('dashboard/actionUrl/', site_allocation_listview, name='actionUrl'),
    path('fair/actionUrl/', FairCreateView.as_view(), name='actionUrl'),
    path('event/actionUrl/', EventCreateView.as_view(), name='actionUrl'),
    path('zone/actionUrl/', ZoneCreateView.as_view(), name='actionUrl'),
    path('site/actionUrl/', SiteCreateView.as_view(), name='actionUrl'),
    path('siteallocation/', site_allocation_listview, name='siteallocation-list'),
    path('siteallocation/<int:pk>/edit', SiteAllocationUpdateView.as_view(), name='siteallocation-detail'),
    path('siteallocation/<int:pk>/remove', siteallocation_delete_view, name='siteallocation-remove'),
    path('siteallocation/select', stallholder_select, name='stallholder-select'),
    path('siteallocation/create/', site_allocation_create, name='siteallocation-create'),
    path('eventsite/actionUrl/', EventSiteCreateView.as_view(), name='actionUrl'),
    path('inventoryitem/actionUrl/', InventoryItemCreateView.as_view(), name='actionUrl'),
    path('inventoryitemfair/actionUrl/', InventoryItemFairCreateView.as_view(), name='actionUrl'),
    path('powerbox/actionUrl/', PowerBoxCreateView.as_view(), name='actionUrl'),
    path('eventpower/actionUrl/', EventPowerCreateView.as_view(), name='actionUrl'),
    path('fair/comment/done/<int:pk>/', set_message_to_done, name='is-done'),
    path('fair/comment/active/<int:pk>/', set_message_to_active, name='is-active'),
    path('fair/unpoweredsites/', stallregistrations_without_power_view, name='sites-without-power'),
    path('fair/powerboxconnections/', powerbox_connections_view, name='powerbox-connections'),
    path('fair/powerboxsiteallocations/', stallregistrations_by_powerbox_view, name='powerbox-stallregistration-list'),
]
